# Use an official Node runtime as the base image
FROM node:18.15.0-alpine

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .

ENV NODE_ENV=development

# Expose the React app's default port (3000)
EXPOSE 3000

CMD ["yarn", "start"]
