# Use an official Node runtime as the base image
FROM node:18.15.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the current directory contents into the container
COPY . .

# Set the environment to development (optional)
ENV NODE_ENV=development

# Expose the React app's default port (3000)
EXPOSE 3000

# Start the app using the development server
CMD ["npm", "start"]
