version: "3.8"

services:
  postgres:
    image: "postgres:11"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=auction
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    command: >
      sh -c "
        npx prisma migrate deploy
        yarn start:dev
      "
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "8000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - JWT_SECRET=My!ecret007
      - DATABASE_URL=postgres://postgres:postgres_password@postgres:5432/auction
      - CRYPTR_SECRET=CS3crEt123
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
