version: "3.8"

services:
  postgres:
    image: "postgres:11"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "5432:5432"
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "8000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - JWT_SECRET=My!ecret007
